import { PackageSummary } from './package';

// A percentage-off promo code an admin creates and a buyer applies when buying
// a package. The `code` is generated by the API. A coupon is linked to one or
// more packages and applies only to those; `percentOff` is 1–100. At 100 the
// package is free — the buy flow settles it without charging the gateway.
export type BaseCoupon = {
  id: string;
  code: string;
  percentOff: number;
  isActive: boolean;
  packages: PackageSummary[]; // the package(s) this coupon applies to (>= 1)
  createdAt: string;
};

export type CreateCouponBody = {
  percentOff: number; // 1–100 (100 = free registration)
  isActive?: boolean; // default true
  packageIds: string[]; // required, at least one package
};

// `code` is immutable/API-generated and cannot be changed after creation.
export type UpdateCouponBody = {
  percentOff?: number;
  isActive?: boolean;
  packageIds?: string[]; // when present, replaces the linked set (>= 1)
};

// Buyer-facing preview: check a code against a package, get the computed price.
export type ValidateCouponBody = {
  code: string;
  packageId: string;
};

export type ValidateCouponResponse = {
  code: string; // the coupon's stored (uppercased) code
  percentOff: number;
  originalAmount: number; // package price, pesewas
  discountAmount: number; // amount taken off, pesewas
  netAmount: number; // what the buyer would be charged, pesewas (0 at 100% off)
};
